_target_: pytorch_lightning.Trainer
gradient_clip_val: 0.5
accumulate_grad_batches: null
max_epochs: 50
min_epochs: 1
accelerator: "auto"     # set gpu or cpu automatically
strategy:
  _target_: pytorch_lightning.strategies.DDPStrategy
  find_unused_parameters: false
precision: 32
