_target_: pytorch_lightning.Trainer
gradient_clip_val: 0.5
accumulate_grad_batches: ${accumulate_grad_batches}
max_epochs: 10
min_epochs: 1
accelerator: "auto"     # set gpu or cpu automatically
strategy: ddp
precision: 32
