ci:
  autofix_prs: false
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        exclude: "kwja/resource/.*"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies:
          - rhoknp==1.6.0
          - hydra-core==1.3.2
          - torch==2.7.0
          - torchmetrics==1.7.0
          - transformers==4.50.3
          - tokenizers
          - wandb
          - rich
          - typer-slim
          - types-PyYAML
          - cohesion-tools==0.7.5
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
        files: ^scripts/
        types: [ shell ]
        args: [ --exclude=SC2002 ]
