[tool.poetry]
name = "jula"
version = "0.1.0"
description = "A unified language analyzer for Japanese"
authors = [
    "Hirokazu Kiyomaru <kiyomaru@i.kyoto-u.ac.jp>",
    "Nobuhiro Ueda <ueda@nlp.i.kyoto-u.ac.jp>",
    "Kazumasa Omura <omura@nlp.i.kyoto-u.ac.jp>",
    "Takashi Kodama <kodama@nlp.i.kyoto-u.ac.jp>",
    "Yugo Murawaki <murawaki@i.kyoto-u.ac.jp>",
    "Daisuke Kawahara <dkw@waseda.jp>",
    "Sadao Kurohashi <kuro@i.kyoto-u.ac.jp>"
]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
torch = "~1.11.0"
pytorch-lightning = "^1.6"
omegaconf = "^2.1"
hydra-core = "^1.2"
tokenizers = "^0.12.1"
transformers = "~4.19.2"
typer = "^0.4.1"
sentencepiece = "^0.1.96"
protobuf = "~3.20"
seqeval = "^1.2.2"
wandb = "^0.12.17"
rich = "^12.4.4"
rhoknp = {git = "https://github.com/ku-nlp/rhoknp.git", rev = "coreference"}
python-Levenshtein = "^0.12.2"
fugashi = "^1.1.2"
ipadic = "^1.0.0"
python-dotenv = "^0.20.0"
pandas = "^1.4.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1"
pytest-cov = "^3.0.0"

[tool.poetry.scripts]
jula = "jula.cli.cli:app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
