_target_: pytorch_lightning.loggers.WandbLogger
name: ${name}-${hydra:job.num}
save_dir: ${work_dir}
project: ${project}
group: ${name}
tags:
  - sample
settings:
  _target_: wandb.Settings
  start_method: fork
