defaults:
  - /datamodule/base/char@
  - _self_

_target_: kwja.datamodule.datasets.CharInferenceDataset
doc_id_prefix: null
# texts and raw_text_file are mutually exclusive
texts: []
raw_text_file: null
