defaults:
  - base
  - callbacks: [early_stopping, model_checkpoint, model_summary, prediction_writer, progress_bar]
  - datamodule: char
  - dataset: kwdlc
  - logger: wandb
  - model: char_roberta
  - module: char
  - optimizer: adamw
  - trainer: default
  - _self_

devices: ${oc.env:GPUS,0}
do_predict_after_train: True
