typo: [
  "typo_corrector",
  "typo_corrector.debug",
]
char: [
  "word_segmenter",
  "word_segmenter.debug",
]
word: [
  "word_analyzer",
  "word_analyzer.debug",
  "word_module",
  "word_module.debug",
]
