cls:
  _target_: kwja.modules.seq2seq.Seq2SeqModule

tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: ${encoder.pretrained_model_name_or_path}
  additional_special_tokens: ${special_tokens}
  _convert_: all

load_from_checkpoint:
  _target_: ${module.cls._target_}.load_from_checkpoint
  checkpoint_path: ${checkpoint_path}
  strict: false
