_target_: pytorch_lightning.Trainer
accelerator: "auto"     # set gpu or cpu automatically
accumulate_grad_batches: 1
gradient_clip_val: 0.5
max_epochs: 3
min_epochs: 1
strategy: ddp
fast_dev_run: 3
#limit_train_batches: 10
#limit_val_batches: 10
#limit_test_batches: 10
