_target_: pytorch_lightning.Trainer
accelerator: "auto"     # set gpu or cpu automatically
accumulate_grad_batches: 1
precision: 32
gradient_clip_val: 0.5
log_every_n_steps: 100
max_epochs: 50
min_epochs: 1
strategy: ddp
