defaults:
  - train:
    - kyoto.yaml
    - kwdlc.yaml
    - fuman.yaml
  - valid:
    - kyoto.yaml
    - kwdlc.yaml
    - fuman.yaml
  - test:
    - kyoto.yaml
    - kwdlc.yaml
    - fuman.yaml

tokenizer_kwargs:
  additional_special_tokens: []
