data_dir: ${oc.env:DATA_DIR}/typo_correction
extended_vocab_path: ${oc.env:DATA_DIR}/typo_correction/freq>=2.txt
extended_vocab_size: 358
tokenizer_kwargs:
  do_word_tokenize: False
  additional_special_tokens: ["<k>","<d>","<_>","<dummy>"]
