defaults:
  - train:
    - jwtd.yaml
  - valid:
    - jwtd.yaml
  - test:
    - jwtd.yaml

extended_vocab_path: ${oc.env:DATA_DIR}/typo_correction/multi_char_vocab.txt
extended_vocab_size: 359
tokenizer_kwargs:
  do_word_tokenize: False
  additional_special_tokens: ["<k>","<d>","<_>","<dummy>"]
