defaults:
  - train:
    - word_kyoto.yaml
    - word_kwdlc.yaml
    - word_fuman.yaml
  - valid:
    - word_kyoto.yaml
    - word_kwdlc.yaml
    - word_fuman.yaml
  - test:
    - word_kyoto.yaml
    - word_kwdlc.yaml
    - word_fuman.yaml
  - predict:
    - word_inference.yaml

special_tokens: ${concat:${exophora_referents},["[NULL]", "[NA]", "[ROOT]"]}
tokenizer_kwargs:
  additional_special_tokens: ${dataset.special_tokens}
  _convert_: all
