tokenizer_kwargs:
  additional_special_tokens: ${dataset.special_tokens}
  _convert_: all
reading_resource_path: kwja/resource/reading_prediction
special_tokens: ${concat:${exophora_referents},["[NULL]", "[NA]", "[ROOT]"]}
