_target_: kwja.datamodule.datasets.char_dataset.CharDataset
model_name_or_path: ${encoder.model_name_or_path}
max_seq_length: ${encoder.max_seq_length}
tokenizer_kwargs: ${dataset.tokenizer_kwargs}
document_split_stride: ${document_split_stride}
denormalize_prob: ${denormalize_prob}
