_target_: kwja.datamodule.datasets.char_dataset.CharDataset
document_split_stride: ${document_split_stride}
model_name_or_path: ${encoder.pretrained_model_name_or_path}
tokenizer_kwargs: ${dataset.tokenizer_kwargs}
max_seq_length: ${max_seq_length}
denormalize_probability: ${denormalize_probability}
