_target_: jula.datamodule.datasets.char_dataset.CharDataset
wiki_ene_dic_path: ${dataset.wiki_ene_dic_path}
max_ene_num: ${dataset.max_ene_num}
model_name_or_path: ${model.model_name_or_path}
max_seq_length: ${model.max_seq_length}
tokenizer_kwargs: ${dataset.tokenizer_kwargs}
document_split_stride: ${document_split_stride}
