_target_: kwja.datamodule.datasets.CharDataset
max_seq_length: ${max_seq_length}
denormalize_probability: ${denormalize_probability}
tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: ${encoder.pretrained_model_name_or_path}
  do_word_tokenize: false
  _convert_: all
