_target_: kwja.datamodule.datasets.SenterDataset
max_seq_length: ${max_seq_length}
document_split_stride: ${document_split_stride}
tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: ${encoder.config.pretrained_model_name_or_path}
  do_word_tokenize: false
  _convert_: all
