_target_: kwja.datamodule.datasets.typo_dataset.TypoDataset
max_seq_length: ${max_seq_length}
extended_vocab_path: ${dataset.extended_vocab_path}
tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: ${encoder.pretrained_model_name_or_path}
  do_word_tokenize: false
  additional_special_tokens: ${dataset.special_tokens}
  _convert_: all
