_target_: kwja.datamodule.datasets.TypoDataset
max_seq_length: ${max_seq_length}
tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: ${encoder.config.pretrained_model_name_or_path}
  do_word_tokenize: false
  additional_special_tokens: ${special_tokens}
  _convert_: all
