_target_: jula.datamodule.datasets.typo_dataset.TypoDataset
extended_vocab_path: ${dataset.extended_vocab_path}
model_name_or_path: ${model.model_name_or_path}
max_seq_length: ${model.max_seq_length}
tokenizer_kwargs: ${dataset.tokenizer_kwargs}
