_target_: kwja.datamodule.datasets.typo_dataset.TypoDataset
model_name_or_path: ${encoder.pretrained_model_name_or_path}
tokenizer_kwargs: ${dataset.tokenizer_kwargs}
max_seq_length: ${max_seq_length}
extended_vocab_path: ${dataset.extended_vocab_path}
