_target_: kwja.datamodule.datasets.WordDataset
max_seq_length: ${max_seq_length}
document_split_stride: ${document_split_stride}
cohesion_tasks: ${cohesion_tasks}
exophora_referents: ${exophora_referents}
restrict_cohesion_target: ${restrict_cohesion_target}
pas_cases: ${pas_cases}
br_cases: ${br_cases}
special_tokens: ${special_tokens}
tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: ${encoder.config.pretrained_model_name_or_path}
  additional_special_tokens: ${special_tokens}
  _convert_: all
