_target_: kwja.datamodule.datasets.word_dataset.WordDataset
document_split_stride: ${document_split_stride}
max_seq_length: ${max_seq_length}
pas_cases: ${pas_cases}
bar_rels: ${bar_rels}
exophora_referents: ${exophora_referents}
cohesion_tasks: ${cohesion_tasks}
restrict_cohesion_target: ${restrict_cohesion_target}
special_tokens: ${dataset.special_tokens}
tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: ${encoder.pretrained_model_name_or_path}
  additional_special_tokens: ${dataset.special_tokens}
  _convert_: all
