prediction_writer:
  _target_: kwja.callbacks.typo_module_writer.TypoModuleWriter
  output_dir: ${run_dir}
  confidence_threshold: ${confidence_threshold}
  extended_vocab_path: ${dataset.extended_vocab_path}
  output_filename: "predict"
  tokenizer:
    _target_: transformers.AutoTokenizer.from_pretrained
    pretrained_model_name_or_path: ${encoder.pretrained_model_name_or_path}
    do_word_tokenize: false
    additional_special_tokens: ${dataset.special_tokens}
    _convert_: all
