prediction_writer:
  _target_: jula.callbacks.typo_module_writer.TypoModuleWriter
  output_dir: ${run_dir}
  extended_vocab_path: ${dataset.extended_vocab_path}
  confidence_threshold: ${confidence_threshold}
  pred_filename: "predict"
  model_name_or_path: ${model.model_name_or_path}
  tokenizer_kwargs: ${dataset.tokenizer_kwargs}
