prediction_writer:
  _target_: kwja.callbacks.TypoModuleWriter
  confidence_threshold: ${confidence_threshold}
  destination: ${run_dir}/typo_prediction.txt
  tokenizer:
    _target_: transformers.AutoTokenizer.from_pretrained
    pretrained_model_name_or_path: ${encoder.pretrained_model_name_or_path}
    do_word_tokenize: false
    additional_special_tokens: ${special_tokens}
    _convert_: all
