prediction_writer:
  _target_: kwja.callbacks.typo_module_writer.TypoModuleWriter
  output_dir: ${run_dir}
  confidence_threshold: ${confidence_threshold}
  extended_vocab_path: ${dataset.extended_vocab_path}
  output_filename: "predict"
  model_name_or_path: ${encoder.pretrained_model_name_or_path}
  tokenizer_kwargs: ${dataset.tokenizer_kwargs}
