prediction_writer:
  _target_: kwja.callbacks.word_module_writer.WordModuleWriter
  output_dir: ${run_dir}
  reading_resource_path: ${dataset.reading_resource_path}
  ambig_surf_specs:
    - conjtype: "イ形容詞アウオ段"
      conjform: "エ基本形"
    - conjtype: "イ形容詞イ段"
      conjform: "エ基本形"
    - conjtype: "イ形容詞イ段特殊"
      conjform: "エ基本形"
  jumandic_path: kwja/resource/jumandic
  output_filename: "predict"
