prediction_writer:
  _target_: jula.callbacks.word_module_writer.WordModuleWriter
  output_dir: ${run_dir}
  pred_filename: "predict"
  model_name_or_path: ${model.model_name_or_path}
  tokenizer_kwargs: ${dataset.tokenizer_kwargs}
