prediction_writer:
  _target_: kwja.callbacks.WordModuleWriter
  ambig_surf_specs:
    - conjtype: "イ形容詞アウオ段"
      conjform: "エ基本形"
    - conjtype: "イ形容詞イ段"
      conjform: "エ基本形"
    - conjtype: "イ形容詞イ段特殊"
      conjform: "エ基本形"
  destination: ${run_dir}/word_prediction.knp
