defaults:
  - base
  - callbacks: [early_stopping, model_checkpoint, model_summary, char_module_writer, progress_bar]
  - datamodule: char
  - dataset: char
  - logger: wandb
  - encoder: char_roberta_large
  - module: char
  - optimizer: adamw
  - scheduler: constant_schedule_with_warmup
  - trainer: default
  - _self_

max_seq_length: 512
do_predict_after_train: true
checkpoint_path: ""
document_split_stride: -1

# For word normalization
denormalize_probability: 0.0

# set monitor and mode for early_stopping and model_checkpoint
monitor: valid/aggregated_char_metrics
mode: max
aggregating_metrics:
  - word_segmentation_f1
#  - word_normalization_f1  # exclude because this metric is unstable

# hyper-parameters to be tuned
warmup_steps: 100
effective_batch_size: 16

# environment dependent settings
devices: ${oc.env:GPUS,0}
max_batches_per_device: 2
num_workers: 0

ignore_hparams_on_save: false
hparams_to_ignore_on_save:
  - project
  - work_dir
  - seed
  - name
  - exp_dir
  - run_id
  - run_dir
  - config_name
  - callbacks:
    - early_stopping
    - model_checkpoint
    - model_summary
    - prediction_writer:
        - output_dir
  - datamodule:
    - train
    - valid
    - test
  - logger
  - hparams_to_ignore_on_save
