defaults:
  - callbacks: [progress_bar.yaml]
  - logger: null
  - module: null  # typo, char, seq2seq, or word
  - _self_

# required settings
checkpoint_path: null  # path to trained checkpoint
eval_set: test  # test or valid

# TODO: fix `test.py`, `predict.py`, and `analyze.py` for the following settings to take effect

document_split_stride: 1

# for typo correction
confidence_threshold: 0.9

# for word normalization
denormalize_probability: 0.0

# for dependency parsing
dependency_topk: 4

# discourse relation analysis
discourse_threshold: 0.0

# environment dependent settings
num_workers: ${oc.env:NUM_WORKERS,0}
devices: ${oc.env:DEVICES,1}
max_batches_per_device: ${oc.env:MAX_BATCHES_PER_DEVICE,2}
compile: ${oc.env:COMPILE,false}
