defaults:
  - base
  - callbacks: [early_stopping, model_checkpoint, model_summary, typo_corrector_writer, progress_bar]
  - datamodule: typo
  - dataset: jwtd
  - logger: wandb
  - model: char_roberta_base
  - module: default
  - optimizer: adamw
  - trainer: default
  - _self_

devices: ${oc.env:GPUS,0}
do_predict_after_train: True
checkpoint_path: ""

# set monitor and mode for early_stopping and model_checkpoint
monitor: valid/loss
mode: min
# batch size
batch_size: 4
accumulate_grad_batches: 16
