defaults:
  - base
  - callbacks: [typo_module_writer, early_stopping, lr_monitor, model_checkpoint, model_summary, progress_bar]
  - datamodule: typo
  - logger: wandb
  - encoder: char_deberta_large
  - module: typo
  - optimizer: adamw
  - scheduler: cosine_schedule_with_warmup
  - trainer: default
  - _self_

max_seq_length: 256
do_predict_after_train: true
checkpoint_path: ""

# set monitor and mode for early_stopping and model_checkpoint
monitor: valid/typo_correction_0.0_f1
mode: max

# option
confidence_threshold: 0.9   # valid only for inference

# hyper-parameters to be tuned
lr: 2e-5
max_epochs: 20
warmup_steps: 1000
effective_batch_size: 176

# environment dependent settings
devices: ${oc.env:DEVICES,0}
max_batches_per_device: ${oc.env:MAX_BATCHES_PER_DEVICE,2}
num_workers: ${oc.env:NUM_WORKERS,4}
compile: ${oc.env:COMPILE,false}

ignore_hparams_on_save: false

# constants
special_tokens: ["<k>", "<d>", "<_>", "<dummy>", " "]
hparams_to_ignore_on_save:
  - project
  - work_dir
  - seed
  - name
  - exp_dir
  - run_id
  - run_dir
  - config_name
  - callbacks:
    - early_stopping
    - model_checkpoint
    - model_summary
    - prediction_writer:
        - destination
  - datamodule:
    - train
    - valid
    - test
  - logger
  - hparams_to_ignore_on_save
