defaults:
  - base
  - callbacks: [early_stopping, model_checkpoint, model_summary, progress_bar]
  - datamodule: typo
  - dataset: typo_dataset
  - logger: wandb
  - model: char_roberta_base
  - module: default
  - optimizer: adamw
  - scheduler: constant_schedule_with_warmup
  - trainer: debug
  - _self_

devices: ${oc.env:GPUS,0}
do_predict_after_train: False

# set monitor and mode for early_stopping and model_checkpoint
monitor: valid/loss
mode: min
# batch size
batch_size: 4
accumulate_grad_batches: 1
