defaults:
  - base
  - callbacks: [early_stopping, model_checkpoint, model_summary, word_module_writer, progress_bar]
  - datamodule: word
  - dataset: word_dataset
  - logger: wandb
  - model: word_roberta_base
  - module: default
  - optimizer: adamw
  - scheduler: constant_schedule_with_warmup
  - trainer: default
  - _self_

devices: ${oc.env:GPUS,0}
do_predict_after_train: True
checkpoint_path: ""

# for dependency parser
k: 4

# for cohesion analysis
cases: ["ガ", "ヲ", "ニ", "ガ２"]
bar_rels: ["ノ"]
exophora_referents: ["著者", "読者", "不特定:人", "不特定:物"]
cohesion_tasks: [pas_analysis, bridging, coreference]  # pas_analysis, bridging, and/or coreference

# set monitor and mode for early_stopping and model_checkpoint
monitor: valid/aggregated_word_metrics
mode: max
aggregating_metrics: [
  "word_analysis_f1",
  "macro_word_feature_f1",
  "macro_base_phrase_feature_f1",
  "base_phrase_LAS_f1",
  "pas_all_case",
  "discourse_parsing_f1_no_relation_ignored",
]
# batch size
batch_size: 4
accumulate_grad_batches: 1
# scheduler options
warmup_steps: 100
