defaults:
  - base
  - callbacks: [early_stopping, model_checkpoint, model_summary, progress_bar]
  - datamodule: word
  - dataset: word_dataset
  - logger: wandb
  - model: word_roberta_base
  - module: default
  - optimizer: adamw
  - trainer: debug
  - _self_

devices: ${oc.env:GPUS,0}
do_predict_after_train: False

# for cohesion analysis
cases: ["ガ", "ヲ", "ニ", "ガ２"]
bar_rels: ["ノ", "ノ？"]
exophora_referents:
  - 著者
  - 読者
  - 不特定:人
  - 不特定:物
cohesion_tasks: [pas_analysis, bridging, coreference]  # pas_analysis, bridging, and/or coreference

# set monitor and mode for early_stopping and model_checkpoint
monitor: valid/f1
mode: max
# batch size
batch_size: 4
accumulate_grad_batches: 1
