defaults:
  - base
  - callbacks: [early_stopping, model_checkpoint, model_summary, phrase_analysis_writer, progress_bar]
  - datamodule: word
  - dataset: word_dataset
  - logger: wandb
  - model: word_roberta_base
  - module: default
  - optimizer: adamw
  - trainer: default
  - _self_

devices: ${oc.env:GPUS,0}
do_predict_after_train: True
checkpoint_path: ""

# set monitor and mode for early_stopping and model_checkpoint
monitor: valid/f1
mode: max
# batch size
batch_size: 8
accumulate_grad_batches: 1
