defaults:
  - base
  - callbacks: [early_stopping, model_checkpoint, model_summary, progress_bar]
  - datamodule: char
  - dataset: kwdlc
  - logger: wandb
  - model: char_roberta_base
  - optimizer: adamw
  - trainer: debug
  - _self_

devices: ${oc.env:GPUS,0}
do_predict_after_train: False

# set monitor and mode for early_stopping and model_checkpoint
monitor: valid/f1
mode: max
