defaults:
  - base
  - callbacks: [early_stopping, model_checkpoint, model_summary, progress_bar]
  - datamodule: word
  - dataset: word
  - logger: wandb
  - model: word_roberta_base
  - module: word
  - optimizer: adamw
  - scheduler: constant_schedule_with_warmup
  - trainer: debug
  - _self_

do_predict_after_train: False
checkpoint_path: ""
document_split_stride: 1

# for dependency parser
k: 4

# for cohesion analysis
cases: ["ガ", "ヲ", "ニ", "ガ２"]
bar_rels: ["ノ"]
exophora_referents: ["著者", "読者", "不特定:人", "不特定:物"]
cohesion_tasks: [pas_analysis, bridging, coreference]  # pas_analysis, bridging, and/or coreference
restrict_cohesion_target: True

# set monitor and mode for early_stopping and model_checkpoint
monitor: valid/aggregated_word_metrics
mode: max
aggregating_metrics: [
  "word_analysis_f1",
  "ner_f1",
  "macro_word_feature_f1",
  "macro_base_phrase_feature_f1",
  "base_phrase_LAS_f1",
  "pas_all_case",
  "discourse_parsing_f1_no_relation_ignored",
]

# hyper-parameters to be tuned
warmup_steps: 100
effective_batch_size: 16

# environment dependent settings
devices: ${oc.env:GPUS,0}
max_batches_per_device: 2
num_workers: 0
