defaults:
  - train:
    - char_kyoto.yaml
    - char_kyoto_ed.yaml
    - char_kwdlc.yaml
    - char_fuman.yaml
    - char_wac.yaml
  - valid:
    - char_kyoto.yaml
    - char_kwdlc.yaml
    - char_fuman.yaml
    - char_wac.yaml
  - test:
    - char_kyoto.yaml
    - char_kwdlc.yaml
    - char_fuman.yaml
    - char_wac.yaml
  - predict:
    - char_inference.yaml

batch_size: ${max_batches_per_device}
num_workers: ${num_workers}
