defaults:
  - train:
    - char_kyoto.yaml
    - char_kwdlc.yaml
    - char_fuman.yaml
  - valid:
    - char_kyoto.yaml
    - char_kwdlc.yaml
    - char_fuman.yaml
  - test:
    - char_kyoto.yaml
    - char_kwdlc.yaml
    - char_fuman.yaml
  - predict:
    - char_inference.yaml
