defaults:
  - train:
    - jwtd.yaml
  - valid:
    - jwtd.yaml
  - test:
    - jwtd.yaml
  - predict:
    - typo_inference.yaml

batch_size: ${max_batches_per_device}
num_workers: ${num_workers}
dataset_type: typo
