defaults:
  - train:
    - word_kyoto.yaml
    - word_kwdlc.yaml
    - word_fuman.yaml
  - valid:
    - word_kyoto.yaml
    - word_kwdlc.yaml
    - word_fuman.yaml
  - test:
    - word_kyoto.yaml
    - word_kwdlc.yaml
    - word_fuman.yaml
  - predict:
    - word_inference.yaml
