defaults:
  - train:
    - word_kwdlc.yaml
  - valid:
    - word_kwdlc.yaml
  - test:
    - word_kwdlc.yaml
  - predict:
    - word_inference.yaml

batch_size: ${max_batches_per_device}
num_workers: ${num_workers}
dataset_type: word
