defaults:
  - train:
    - word_kyoto.yaml
    - word_kwdlc.yaml
    - word_fuman.yaml
    - word_wac.yaml
  - valid:
    - word_kyoto.yaml
    - word_kwdlc.yaml
    - word_fuman.yaml
    - word_wac.yaml
  - test:
    - word_kyoto.yaml
    - word_kwdlc.yaml
    - word_fuman.yaml
    - word_wac.yaml
  - predict:
    - word_inference.yaml

batch_size: ${max_batches_per_device}
num_workers: ${num_workers}
