prediction_writer:
  _target_: /path/to/prediction_writer_class  # FIXME (e.g., jula.callbacks.xxx_writer.XXXWriter)
  output_dir: ${run_dir}
  pred_filename: "predict"
  model_name_or_path: ${model.model_name_or_path}
  tokenizer_kwargs: ${dataset.tokenizer_kwargs}
