_target_: transformers.AutoModel.from_config
config:
  _target_: transformers.AutoConfig.from_pretrained
  pretrained_model_name_or_path: nlp-waseda/roberta-large-japanese-seq512
add_pooling_layer: false
