name: Publish

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-publish:
    runs-on: ubuntu-latest
    # https://github.com/pypa/gh-action-pypi-publish?tab=readme-ov-file#trusted-publishing
    environment:
      name: pypi
      url: https://pypi.org/p/kwja
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install Poetry
        run: pipx install poetry
      - name: Add path for Python packages
        run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name: Install dependencies
        run: poetry install --no-interaction --only main --no-cache
      - name: Build package
        run: poetry build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
