name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            [Changelog](https://github.com/ku-nlp/kwja/blob/main/CHANGELOG.md)
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
