name: test

on: [push, pull_request]

jobs:
  test:
    name: Run tests with pytest
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2.1.4
      with:
        python-version: 3.9
    - name: Install Poetry
      run: |
        python3 -m pip install --user pipx
        python3 -m pipx ensurepath
        python3 -m pipx install poetry
    - name: Add path for Python packages
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        poetry config virtualenvs.create false
        poetry install --no-interaction
    - name: Run tests
      run: |
        poetry run pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        name: codecov-umbrella
        verbose: true
