name: Typos

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: typos-action
        uses: crate-ci/typos@v1
